dist: trusty
language: go
go:
- 1.x

install:
  - go get ./...
  - cd front-end && npm install
script:
  - npm run build
  - rm -rf node_modules

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: $HEROKU_API_KEY