dist: trusty
language: go
go:
- 1.x

install:
  - go get ./...
  - cd front-end && npm install
script:
  - npm run build
  - rm -rf node_modules
  - cd ../
  - mv front-end/dist .
  - rm -rf front-end

deploy:
  provider: heroku
  skip_cleanup: true
  app: user-demo-go-vue
  api_key:
    secure: $HEROKU_API_KEY